version: "3"
services:
  mysql:
    image: "mysql:5.7"
    restart: "always"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "ivGP5eI6cmANoMUp"
    ports:
      - "3306:3306"
    volumes:
      - "./my.cnf:/etc/mysql/my.cnf"
      - "./data:/var/lib/mysql"
